apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-laboratorio
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-laboratorio
    spec:
      containers:
      - name: api-laboratorio
        image: mplbruno/apiadminubu	
        ports:
        - containerPort: 5000
        env: 
        - name: ASPNETCORE_URLS
          value: http://*:5000
  selector:
    matchLabels:
        app: api-laboratorio
  
